services:
  - docker
before_install:
  - docker pull cirrusci/flutter:dev-web
install:
  - DOCKER_BUILDKIT=1 docker build --secret username=$github_username,password=$github_password --tag ishaq:1.0 .
